# Generated by Django 3.0.7 on 2020-07-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='imagen',
        ),
    ]
