# Generated by Django 3.0.7 on 2020-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200716_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='imagen',
        ),
        migrations.AddField(
            model_name='project',
            name='descriptions',
            field=models.TextField(default=' ', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=' ', upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='project',
            name='mail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion'),
        ),
    ]
